export const skills = [
    { nombre: "JavaScript", rating: 4.5 },
    { nombre: "React.js", rating: 4.0 },
    { nombre: "Node.js", rating: 4.0 },
    { nombre: "Express.js", rating: 3 },
    { nombre: "MongoDB", rating: 4 },
    { nombre: "Mongoose", rating: 3.5 },
    { nombre: "HTML5", rating: 4.5 },
    { nombre: "Hojas de estilos en cascada (CSS)", rating: 4 },
    { nombre: "Git", rating: 4 },
    { nombre: "API de Postman", rating: 4 },
    { nombre: "Scrum", rating: 4 },
    { nombre: "Metodologías ágiles", rating: 4 },
    { nombre: "C#", rating: 4 },
    { nombre: ".NET Framework", rating: 3.5 },
    { nombre: "SQL", rating: 4.5 },
    { nombre: "MySQL", rating: 4.5 },
    { nombre: "Diseño de bases de datos", rating: 4.0 },
    { nombre: "Base de datos relacional", rating: 4.0 },
    { nombre: "Desarrollo de base de datos", rating: 4.0 },
    { nombre: "Docker", rating: 3 },
    { nombre: "Desarrollo ágil de aplicaciones", rating: 4.0 },
    { nombre: "Programación orientada a objetos (POO)", rating: 4.5 },
    { nombre: "Programación", rating: 5 },
    { nombre: "Desarrollo de software", rating: 4 },
    { nombre: "Desarrollo web", rating: 4.5 },
    { nombre: "JIRA", rating: 3 },
    { nombre: "HTML", rating: 5 },
    { nombre: "CentOS", rating: 3 },
    { nombre: "Ansible", rating: 2 },
    { nombre: "Zabbix", rating: 2 },
    { nombre: "Red Hat Linux", rating: 3 },
    { nombre: "Aseguramiento de la calidad", rating: 4 },
    { nombre: "Fundamentos Cyber de Redes", rating: 2 },
    { nombre: "LAN-WAN", rating: 4 },
    { nombre: "Sistemas operativos", rating: 3.5 },
    { nombre: "Cableado estructurado", rating: 4 },
    { nombre: "Reparación de equipos informáticos", rating: 3 },
    { nombre: "Trabajo en equipo", rating: 5 },
    { nombre: "Java", rating: 3.5 },
    { nombre: "Java SE", rating: 3 },
    { nombre: "Bases de datos", rating: 4.5 }
  ];
  